name: PSScriptAnalyzer
on:
  pull_request:
jobs:
  lint:
    name: PSScriptAnalyzer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PSScriptAnalyzer checks
        uses: devblackops/github-action-psscriptanalyzer@master
        with:
          sendComment: true
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          failOnErrors: true
          failOnWarnings: false
          failOnInfos: false