name: Check for updates

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run-script:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install AU
      run: Install-Module au -Force

    - name: Run PowerShell script
      run: ./choco/update_all.ps1

    - name: Check if changes were made
      id: check-changes
      run: |
        if (git diff --exit-code) {
          echo "No changes were made."
          exit 1
        }
        echo "Changes were made."
        exit 0
  
    - name: Pack and push packages
      if: steps.check-changes.outputs.exit_code == 0
      uses: crazy-max/ghaction-chocolatey@v2
      run: |
        # Get a list of changed folders
        changed_folders=$(git diff-tree --no-commit-id --name-only -r HEAD | grep "^choco/" | xargs dirname | sort -u)
        
        # Pack only changed folders
        for folder in $changed_folders; do
          echo "Packing $folder..."
          choco pack $folder -y
          echo "Pushing $folder..."
          choco push $folder/*.nupkg --source https://push.chocolatey.org/ --api-key ${{ secrets.CHOCO_API_KEY }}
        done
    
    - name: Commit changes
      if: steps.check-changes.outputs.exit_code == 0
      run: |
        git config --local user.email "eric@bostrot.com"
        git config --local user.name "Eric"
        git add .
        git commit -m "Update package"

    - name: Push changes
      if: steps.check-changes.outputs.exit_code == 0
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ env.GITHUB_TOKEN }}