name: Check for updates

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run-script:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install AU
      run: Install-Module au -Force

    - name: Install chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
  
    - name: Run PowerShell script
      run: ./update_script.ps1
      env:
        CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}

    - name: Check if changes were made
      id: check-changes
      run: |
        if (git diff --exit-code) {
          echo "Changes were made"
          echo "::set-output name=changes::true"
        } else {
          echo "No changes were made"
          echo "::set-output name=changes::false"
        }

    - name: Push changes
      if: steps.check-changesoutput.changes == 'true'
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ env.GITHUB_TOKEN }}
