name: Check for updates

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run-script:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install AU
      run: Install-Module au -Force

    - name: Run PowerShell script
      run: ./choco/update_all.ps1

    - name: Check if changes were made
      id: check-changes
      run: |
        if (git diff --exit-code) {
          echo "No changes were made."
          exit 0
        }

        echo "Changes were made."
    
    - name: Commit changes
      if: steps.check-changes.outputs.exit_code == 0
      run: |
        git config --local user.email "eric@bostrot.com"
        git config --local user.name "Eric"
        git add .
        git commit -m "Update package"

    - name: Push changes
      if: steps.check-changes.outputs.exit_code == 0
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ env.GITHUB_TOKEN }}
